import Head from "next/head";
import Blog from "../components/Blog";
import Current from "../components/Current";
import Footer from "../components/Footer";
import GoTo from "../components/GoTo";
import Grid from "../components/Grid";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="relative w-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className=" relative w-screen">
        {" "}
        {/* <div className="bg-slate-100 fixed h-[1.5rem] my-auto inline-flex right-0 -rotate-90 ">
          <img src="../assets/sms.svg" alt="" />
          <p>Feedback</p>
        </div> */}
        <Grid />
        <Current />
        <Blog />
        <GoTo />
        <Footer />
      </div>
    </div>
  );
}
